#!/usr/bin/env bash
# Give the Arduino motor board and the LD19 laser stable names, so a board reset
# cannot make them swap /dev/ttyUSB numbers.
#
#   ./setup_udev.sh            inspect the attached devices and print the rules
#   ./setup_udev.sh --install  write them to /etc/udev/rules.d and reload
#
# Run this ON THE ROBOT, with both devices plugged in.
set -euo pipefail

RULES_FILE=/etc/udev/rules.d/99-bin-robot.rules
INSTALL=0
[ "${1:-}" = "--install" ] && INSTALL=1

ports=(/dev/ttyUSB*)
if [ ! -e "${ports[0]}" ]; then
    echo "No /dev/ttyUSB* devices found. Plug both in and try again." >&2
    exit 1
fi

echo "Attached USB serial devices"
echo "==========================="
for p in "${ports[@]}"; do
    info=$(udevadm info -q property -n "$p")
    vid=$(sed -n 's/^ID_VENDOR_ID=//p'  <<<"$info")
    pid=$(sed -n 's/^ID_MODEL_ID=//p'   <<<"$info")
    ser=$(sed -n 's/^ID_SERIAL_SHORT=//p' <<<"$info")
    mdl=$(sed -n 's/^ID_MODEL=//p'      <<<"$info")
    path=$(udevadm info -q path -n "$p")
    kernels=$(basename "$(dirname "$(dirname "/sys$path")")")
    printf "  %-14s vendor=%s product=%s serial=%-16s model=%s\n" \
           "$p" "$vid" "$pid" "${ser:-<none>}" "$mdl"
    printf "  %-14s usb port path: %s\n\n" "" "$kernels"
done

cat <<'EOF'
Which is which
--------------
The motor board is the one that answers the ROSArduinoBridge protocol. With the ROS
stack stopped, check a candidate with:

    printf 'e\r' > /dev/ttyUSB0 ; timeout 1 cat /dev/ttyUSB0

Two integers back means that is the Arduino. The other one is the LD19.

EOF

echo "Generating rules..."
echo

# A CH340 has no unique serial number, so two of them cannot be told apart by ID.
# In that case match on the physical USB port instead — which means the devices must
# stay in the same hub sockets. Serial numbers are used when they exist.
tmp=$(mktemp)
{
  echo "# Stable names for the bin robot's USB serial devices."
  echo "# Generated by bin_bringup/udev/setup_udev.sh on $(date -I)."
  echo "# Referenced by bin_real.launch.py as motor_port / lidar_port."
  echo
  for p in "${ports[@]}"; do
      info=$(udevadm info -q property -n "$p")
      vid=$(sed -n 's/^ID_VENDOR_ID=//p'  <<<"$info")
      pid=$(sed -n 's/^ID_MODEL_ID=//p'   <<<"$info")
      ser=$(sed -n 's/^ID_SERIAL_SHORT=//p' <<<"$info")
      path=$(udevadm info -q path -n "$p")
      kernels=$(basename "$(dirname "$(dirname "/sys$path")")")
      echo "# ---- currently $p ---- rename SYMLINK to bin_motors or bin_lidar ----"
      if [ -n "$ser" ]; then
          echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$vid\", ATTRS{idProduct}==\"$pid\", ATTRS{serial}==\"$ser\", SYMLINK+=\"bin_CHANGEME\", MODE=\"0666\""
      else
          echo "# no serial number on this chip — matching the physical USB port instead"
          echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$vid\", ATTRS{idProduct}==\"$pid\", KERNELS==\"$kernels\", SYMLINK+=\"bin_CHANGEME\", MODE=\"0666\""
      fi
      echo
  done
} > "$tmp"

cat "$tmp"

if [ "$INSTALL" = "1" ]; then
    if grep -q bin_CHANGEME "$tmp"; then
        echo "Refusing to install: edit the SYMLINK names first." >&2
        echo "Save the block above, replace each bin_CHANGEME with bin_motors or" >&2
        echo "bin_lidar, then write it to $RULES_FILE yourself and run:" >&2
        echo "  sudo udevadm control --reload-rules && sudo udevadm trigger" >&2
        exit 1
    fi
    sudo cp "$tmp" "$RULES_FILE"
    sudo udevadm control --reload-rules
    sudo udevadm trigger
    echo "Installed $RULES_FILE. Replug both devices, then check:"
    echo "  ls -l /dev/bin_motors /dev/bin_lidar"
fi
rm -f "$tmp"
